"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['start.py']
DATA_FILES = [('bitmaps', ['data/*'])]
OPTIONS = {'argv_emulation': True
           ,'packages' : ['pygame']
           # ,'frameworks' : ['/Library/Python/2.7/site-packages/pygame']
          }

setup(
    app=APP,
    data_files=DATA_FILES,
    name='Escape From Russia',
    version='1.0',
    options={'py2app': OPTIONS},
    install_requires=['pygame'],
    setup_requires=['py2app'],
)
